const assert=require('node:assert/strict');const R=require('../web/engine.js');let s=R.fresh();assert.equal(s.pets.length,4);assert.equal(R.buy(s,'pool'),true);assert.equal(s.coins,50);assert.equal(R.buy(s,'pool'),false);assert.equal(R.buy(s,'house'),false);assert.equal(R.buy(s,'unknown'),false);s.coins=0;assert.equal(R.care(s,'food'),false);s.coins=20;assert.equal(R.care(s,'food'),true);assert.equal(s.coins,15);assert.equal(s.pets[0].food,100);assert.equal(R.care(s,'food'),false);R.reward(s,1000);assert.equal(s.coins,115);R.age(s,s.last+86400000);assert(s.pets[0].food>=15);assert.deepEqual(R.normalize(null).world,Array(R.WORLD_CELLS).fill(null));s.coins=-100;s=R.normalize(s);assert.equal(s.coins,0);console.log('All game rule tests passed');

// El mundo grande conserva el tablero antiguo de 4x4 al migrar.
let oldWorldSave=R.fresh();oldWorldSave.world=Array(16).fill(null);oldWorldSave.world[0]='tree';oldWorldSave.world[15]='house';oldWorldSave=R.normalize(oldWorldSave);assert.equal(oldWorldSave.world.length,R.WORLD_CELLS);assert.equal(oldWorldSave.world[18],'tree');assert.equal(oldWorldSave.world[45],'house');assert.equal(oldWorldSave.world[0],null);
// La actualización conserva partidas de v1.2 sin los campos nuevos.
let legacy=R.fresh();legacy.coins=731;legacy.xp=120;legacy.owned=['bow','house'];legacy.world[4]='house';legacy.pets[0].name='Firulais';legacy.pets[0].accessory='bow';for(const p of legacy.pets){delete p.energy;delete p.sleeping;delete p.sleepSince;delete p.restCounted;}
let migrated=R.normalize(JSON.parse(JSON.stringify(legacy)));assert.equal(migrated.coins,731);assert.equal(migrated.xp,120);assert.equal(migrated.world[4],'house');assert.equal(migrated.pets[0].accessory,'bow');assert.equal(migrated.pets[0].name,'Firulais');assert.equal(migrated.pets[0].energy,80);assert.equal(migrated.pets[0].sleeping,false);
// Premios una sola vez, también después de guardar y volver a abrir.
s=R.fresh();let now=Date.now();assert.equal(R.claim(s,'love',now),0);assert.equal(R.claim(s,'bonus',now),0);R.progress(s,'love',99,now);assert.equal(s.missions.progress.love,3);assert.equal(R.claim(s,'love',now),20);s=R.normalize(JSON.parse(JSON.stringify(s)));assert.equal(R.claim(s,'love',now),0);for(const m of R.missions){R.progress(s,m.id,m.goal,now);R.claim(s,m.id,now);}assert.equal(R.ready(s,now),1);assert.equal(R.claim(s,'bonus',now),40);assert.equal(R.claim(s,'bonus',now),0);assert.equal(s.coins,410);assert.equal(R.ready(s,now),0);
// Reinicio diario sin perder monedas ni permitir cobrar objetivos vacíos.
const tomorrow=new Date(now);tomorrow.setDate(tomorrow.getDate()+1);R.dailyMissions(s,+tomorrow);assert.deepEqual(s.missions.claimed,[]);assert.equal(s.coins,410);assert.equal(R.claim(s,'love',+tomorrow),0);
// Dormir recupera energía; requiere 30 s seguidos para la misión.
s=R.fresh();now=Date.now();s.last=now;s.pets[0].energy=30;assert.equal(R.sleep(s,now),true);assert.equal(R.care(s,'food'),false);assert.equal(R.toy(s,now),false);R.age(s,now+29000);assert.equal(s.missions.progress.rest||0,0);R.age(s,now+30000);assert.equal(s.missions.progress.rest,1);assert.equal(s.pets[0].energy,32);R.age(s,now+600000);assert.equal(s.missions.progress.rest,1);assert.equal(s.pets[0].energy,70);assert.equal(R.sleep(s,now+600000),false);s=R.normalize(JSON.parse(JSON.stringify(s)));assert.equal(s.pets[0].sleeping,false);
s=R.fresh();s.last=now;R.sleep(s,now);R.sleep(s,now+20000);R.age(s,now+40000);assert.equal(s.missions.progress.rest||0,0);
// Pelota y minijuegos incrementan los objetivos sin excederlos.
s=R.fresh();for(let i=0;i<9;i++)assert.equal(R.toy(s,now),true);assert.equal(s.missions.progress.toy,5);assert.equal(s.coins,250);R.reward(s,10);assert.equal(s.missions.progress.game,1);R.reward(s,10);assert.equal(s.missions.progress.game,2);
console.log('Migration, daily missions, reward safety, sleeping and toys passed');

// Only fixed, validated ad rewards are credited, once per durable receipt.
s=R.fresh();assert.equal(R.applyAdReward(s,'receipt-test-001',100),100);assert.equal(s.coins,350);assert.equal(R.applyAdReward(s,'receipt-test-001',100),0);s=R.normalize(JSON.parse(JSON.stringify(s)));assert.equal(R.applyAdReward(s,'receipt-test-001',100),0);assert.equal(R.applyAdReward(s,'receipt-test-002',999),0);assert.equal(R.applyAdReward(s,'short',100),0);assert.equal(s.coins,350);assert.equal(R.applyAdReward(s,'receipt-test-002',100),100);assert.equal(s.coins,450);console.log('Ad reward receipt validation and deduplication passed');
